### PR TITLE
DHTlib: integer fields humidityInt10 and temperatureInt10 were added. #1...

### PR DESCRIPTION
**Pull request by DmitryDzz**
humidityInt10 is an integer humidity value * 10
temperatureInt10 is an integer temperature value * 10

These integer values are useful for LED display output.

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks for this PR, 
As the change is specific - and only useful - for a certain type of display which has no direct relation with the DHT sensors themselves I think it should not be in the DHT class.

That said the thought tickles to make a DHT class that uses no floats at all, which should reduce the footprint of the class sec quite a bit.

**Comment by DmitryDzz** [comment]
Thank you for this project,
And I think that is a great idea to make a class (or maybe classes) without floats. Float operations are too heavy in some cases. I could make this new DHT class in my fork but I am afraid I cannot test it right now as I have no sensor. I will get my DHT22 in a week or two. After that I can do tests and send another PR. Is it OK?

**Comment by RobTillaart** [comment]
You can implement a "DHT10" library that returns temp and humidity in 1/10 units. If you base it on my DHT library please mention this e.g. by means of github URL in the code. Thanks.

**Comment by DmitryDzz** [comment]
That is absolutely yours code. Yes, of course I will mention that. All I plan is to add a lib with integer temperature and humidity fields. I think I can close this PR now.

**Comment by TSWarrender** [comment]
Hi,

I am not sure why I am receiving these emails.  Perhaps up are addressing the wrong address.

Regards.

TS Warrender.

**Comment by RobTillaart** [comment]
@TSWarrender 
goto https://github.com/RobTillaart/Arduino/pull/19#issuecomment-94316733 
and click UNWATCH at the top

**Pull request closed without merging**
