### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ivankravets**
* This library in Web Registry: http://platformio.org/lib/show/1322/RunningAverage
* Specification: [library.json](http://docs.platformio.org/pagee/librarymanager/config.html)
* Library Manager:  http://docs.platformio.org/page/librarymanager/index.html

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks, @RobTillaart! 

Would be good to add all your libraries to our registry. Could you provide descriptions/keywords for the rest libs? We will prepare manifests for you.

**Comment by RobTillaart** [comment]
I've been very busy last year - not even time to visit forum - but my Xmas holiday is near so I  will try to spend an hour or so to add the manifests.

**Comment by ivankravets** [comment]
Thank you! I was impressed that a lot of these libs are not presented in any library registries.

> I will try to spend an hour or so to add the manifests

Cool! Don't hesitate to contact me for any questions.

🎄 Merry Christmas! 🎄

**Comment by RobTillaart** [comment]
These libs were created long before lib registries existed :) I've seen them pop up in  many places 
You can find discussions about a lot of the libs on the Arduino forum.

**Comment by RobTillaart** [comment]
Added most json files,

**Comment by ivankravets** [comment]
Thanks a lot!!! +43 awesome libraries!

* http://platformio.org/lib/search?query=author%253A%2522Rob%20Tillaart%2522

**Comment by RobTillaart** [comment]
Welcome, still todo is the library.properties file for all those libs. 
[need a python script that generates both or convert]

**Comment by RobTillaart** [comment]
@ivankravets 

Been a while ago since we talked (and since this thread).
I was notified that my libraries are not up to date anymore on platformio. - https://github.com/RobTillaart/PCF8574/issues/20

In the past I had a lot of libs under one repository (this one), but I split them up so they all have a repo of their own. Better for tracking issues etc. Guess that at that point something went wrong. 

What can I / we do to fix this ?

All my libs can be found under - https://github.com/RobTillaart/

**Comment by ivankravets** [comment]
Hi @RobTillaart ,

All libraries were switched to their own repositories. The only https://platformio.org/lib/show/5546/MathHelpers does not have its own repository.

See https://platformio.org/lib/search?query=owner:robtillaart

**Comment by RobTillaart** [comment]
@ivankravets 
Yep, MathHelpers is still on my todo list but time is my most scarcest resource.

Thanks for the PR.

**Pull request merged**
