### PR TITLE
fix typos in readme

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by RobTillaart** [comment]
Please reopen PR in - https://github.com/RobTillaart/SET as that is the main development repository

**Comment by thijstriemstra** [comment]
huh? if you don't want people to edit/update this repository, why is it possible to make a pull request (that is now discarded).

**Comment by RobTillaart** [comment]
It is possible because I did not switch it off apparently.

This Arduino repository is a collection of 100+ libraries I wrote in the last 10+ years. In that time version control became more difficult as the history per library was hard to track. Simultaneously library managers in the Arduino IDE, platformio etc popped up and these preferred one repo per library. So I started to create a repo per library so issues could be tracked better, people could select only the libraries they were interested in, better match with the lib managers etc. 

I had the choice to remove this big repo, however as it has been cloned 3000+ times and linked and downloaded even more I decided to keep it alive. If a single repo makes a new release I copy it also into this.

Finally the choice of one repo per library also allowed me to use continuous integration, so every PR made by 3rd party and myself can be tested to some extend. This would be pretty hard to do for this big repo.

I will check your PR against the latest readme.md file and update it.

**Comment by RobTillaart** [comment]
reviewed your PR, and I see all typos are fixed in the latest version.

**Comment by thijstriemstra** [comment]
sorry to have wasted your and my time :(

**Comment by RobTillaart** [comment]
You did not waste my time, 
as the typo's were there and now the library is a bit better thanks to you.

(there are only three persons that can waste my time and they are me myself and I ;)

**Pull request closed without merging**
