### PR TITLE
Support 24XX512 devices, set page sizes according to datasheet.

### PR DESCRIPTION
**Pull request by ifreislich**
Rob,
I had some issues with addressing the 24LC512 devices.  Namely, while the uint16_t type can address the last octet in the device, it is not able to represent the entire length of the storage.  I also had some issues with address wrapping due to signedness of rv in determineSize limiting the maximum detected size to 32k or 16k (I can't remember now and I do not have the full set of devices on hand to test fully).

I have also re-worked the second constructor to take an enum... as the second argument to tell the library explicitly what part is involved so that the page size can be set correctly.  This unfortunately breaks the API so I'm not sure if you're happy with that change.

Additionally, the single argument constructor now calls the  two argument constructor with I2C_EEPROM_UNKNOWN which results in the page size being set to 8 octets. In my opinion this is the only safe page size since it should work with all the devices because a 128 octet page will always be aligned to an 8 octet boundary.  Perhaps the single argument constructor could attempt to determine part, but I don't believe that is entirely safe considering writes are involved and a poorly timed reset or power failure will result in data loss.

### CODE REVIEW

**Comment by RobTillaart** [comment]
Sorry it took so long to respond, so little time so much to do :)
Think you have a point and I need to dive into the datasheets for the details. A quick look at the changes shows that they look good but the existing interface will break, so that will affect all users of the lib. 
For now I keep the issue open as I do not want to loose "backwards compatibility"
thanks sofar

**Comment by RobTillaart** [comment]
relates to issue https://github.com/RobTillaart/Arduino/issues/42

**Comment by ifreislich** [comment]
Rob,

Let me have another go at this patch to give one patch per change.  There are really several issues at play here IIRC.

1.  Signed quantities that should really be unsigned.
2.  Variables of type too small.
3.  Some gratuitous API changes.

**Comment by RobTillaart** [comment]
Sorry to come back so late to this one.
The I2C_eeprom has its own repo now here - https://github.com/RobTillaart/I2C_EEPROM
A lot has changed in the mean time. 

If there are still issues, please open anew one there.
Thanks!

**Pull request closed without merging**
