### PR TITLE
DHTlib to v0.1.20 reduce footprint by using uint8_t as error codes

### PR DESCRIPTION
**Pull request by chaveiro**

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks for this improvement, as it breaks the interface I have to think it over. 

Instead of  uint8_t  I prefer   int8_t = [-128.. 127]    So the failures can still be indicated by the negative values and positives values can be used for different variations of "OK" (future?).  That would not break existing interface I think.

I have no time at the moment to test the impact on footprint, do you have numbers?

**Comment by RobTillaart** [comment]
Did a opportunistic test replacing int by int8_t and on both UNO and MEGA2560 sketch size reduced. (DHT22 test sketch used) .  On the UNO the sketch reduced from 6160 to 6126 bytes => gain 34 bytes. MEGA2560 reduced from 6614 -> 6580 => also 34 bytes (as expected)

Will create a 0.1.20 with the int8_t so I will not merge your changes,

Thanks,

**Comment by chaveiro** [comment]
Hi Rob.
uint8_t and int8_t should take the same size. The original was int (or uint16_t) so the big change is from 16 to 8 bits variables.
I'm not a fan of negative numbers as result code, you can use an enum and work with names instead of values anyway.

**Comment by RobTillaart** [comment]
Enum is a good way to prevent magic numbers, however in the 0.1.xx version I want to keep the interfaces compatible. Going from int16 -> int8 did not break interfaces.

I'm designing a 0.2 version which will break the interface to the sensor to support new features. The handshake with the actual sensor will of course be the same. And yes, enum for status is on the requirements!

**Comment by chaveiro** [comment]
Ok, just for the record this lib is the simplest and best i could found
I did try some different DHT libs available but for my requirement a non blocking one was better. I found one and improved it. Can see it here if it's of your interest https://github.com/chaveiro/DHT22

**Comment by RobTillaart** [comment]
Thanks for the link, 
quick look: delayus() is a critical function as micros() takes quite some time.

**Pull request closed without merging**
